### ISSUE TITLE
2. [EPIC] Handle state of input coins and behavior for chosen snack based on coin state

### ISSUE THREAD

**Issue by WojtekHenszke** [MarcinKrukowski/SnackMachineWithStatePattern#8]
- [ ] App start with 0.
- [ ] App should handle coin inputs in different standard values like (5zl 2 zl 1 zl 0,5 0,2 0,1 0,05 0,02 0,01). Maybe some sort of sub-menu for inputting coins?
- [ ] User can buy snack for inserted coins. App should return change in coins with standard values.

Connected issues:
Please fill in with created tasks
